//
//  Constants.swift
//  Esprit
//
//  Created by Harri SN on 9/16/23.
//

import Foundation

enum Constants {
    static let openAIApiKey = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
}
